name: Build Sync-App Package

on:
  push:
    paths:
      - 'sync-app/**'
  pull_request:
    paths:
      - 'sync-app/**'

jobs:
  build-sync-app:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install sudo and dependencies as root
      - name: Install Dependencies as Root
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel rsync inotify-tools sudo
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          chown -R builder:builder $GITHUB_WORKSPACE

      # Step 3: Build the package as the non-root user
      - name: Build Sync-App Package
        run: |
          cd sync-app
          sudo -u builder makepkg -sf --noconfirm

      # Step 4: Upload the built package as an artifact
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sync-app-package
          path: sync-app/*.pkg.tar.zst

